spring.application.name=newsapp

# ===== DataSource MySQL =====
spring.datasource.url=jdbc:mysql://localhost:3306/news?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Y@ssine2003

# ===== JPA / Hibernate =====
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# ===== Cache Caffeine =====
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=15m

# ===== JWT =====
jwt.secret=${JWT_SECRET:nRIbi8NwAcUAWDMfFRWG79QV3TJt94vndglTgkdG6nv}
jwt.access-token-expiration=3600
jwt.refresh-token-expiration=604800

# ===== NewsAPI =====
newsapi.base-url=https://newsapi.org/v2
newsapi.api-key=${NEWS_API_KEY:197dfba4829042ae9e3eb47a9a535814}
newsapi.cache-ttl-minutes=15

# ===== Admin par defaut =====
admin.default-email=${ADMIN_EMAIL:admin@newsapp.com}
admin.default-password=${ADMIN_PASSWORD:Admin@1234}

# ===== Server =====
server.port=8080

# ===== Logging =====
logging.level.com.news=INFO
logging.level.org.springframework.security=WARN

# ===== OpenAPI =====
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method
